/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.people;

import DAO.PeopleDAO;
import DAOFileImp.FilePeopleDAO;
import javax.swing.JOptionPane;
import model.People;
import report.FileReportGenerator;
import report.PdfReportGenerator;
import report.TxtReportGenerator;

/**
 *
 * @author Mohin Paramasivam
 */
public class Vaccination_Status extends javax.swing.JFrame {
    People people;
    PeopleDAO peopleDao = FilePeopleDAO.getInstance();
    /**
     * Creates new form Vaccination_Status
     */
    public Vaccination_Status() {
        people = People_Dashboard.getLoggedInPeople();
        this.setTitle(people.getName());
        initComponents();
        initInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGenerateTxt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblVaccination1 = new javax.swing.JLabel();
        lblVaccination2 = new javax.swing.JLabel();
        lblPersonalDetails = new javax.swing.JLabel();
        btnGeneratePdf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Vaccination Status");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("First Dose : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Second Dose : ");

        btnGenerateTxt.setText("Generate Txt");
        btnGenerateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateTxtActionPerformed(evt);
            }
        });

        jButton3.setText("Dashboard");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setText("Personal Information:");

        lblVaccination1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblVaccination1.setText("Vaccination incomplete.");

        lblVaccination2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblVaccination2.setText("Vaccination incomplete.");

        lblPersonalDetails.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPersonalDetails.setText("jLabel4");

        btnGeneratePdf.setText("Generate PDF");
        btnGeneratePdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVaccination1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVaccination2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPersonalDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(btnGenerateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnGeneratePdf, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVaccination1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVaccination2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeneratePdf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateTxtActionPerformed
//        // TODO add your handling code here:
        FileReportGenerator reportGenerator = new TxtReportGenerator(people.getName() + "'s Vaccination Status", people.getVaccinationReportGeneratables());
        reportGenerator.saveReport();
        JOptionPane.showMessageDialog(null, "Saved txt report to \"" + reportGenerator.getFilePath() + "\"!");
//        String username_input = jTextField1.getText();
//
//        //get the name of the user from People array based on username supplied
//
//
//
//        /* get vaccination report based on the username supplied by the user
//
//        */
//
//        PeopleDAO peopledao = FilePeopleDAO.getInstance();
//        List<People> people = peopledao.all();
//
//        List<Vaccination> vaccination_data = null;
//
//        String vaccine_id = null;
//
//        List<String> arr_vaccine_report = new ArrayList<String>();
//
//        for (People people_data : people ){
//            if(people_data.getUsername().equals(username_input)){
//                vaccination_data = people_data.getVaccinations();
//        }
//        }
//
//        for(Vaccination vaccination : vaccination_data ){
//            arr_vaccine_report.add(vaccination.getGenerateContent());
//
//        }
//
//        String report_dose1 = arr_vaccine_report.get(0);
//        String report_dose2 = arr_vaccine_report.get(1);
//
//
//        jTextArea2.setText(report_dose1);
//        jTextArea3.setText(report_dose2);
//
//
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnGenerateTxtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        People_Dashboard hframe = new People_Dashboard();
        hframe.setLocationRelativeTo(this);
        hframe.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnGeneratePdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePdfActionPerformed
       FileReportGenerator reportGenerator = new PdfReportGenerator(people.getName() + "'s Vaccination Status", people.getVaccinationReportGeneratables());
        reportGenerator.saveReport();
        JOptionPane.showMessageDialog(null, "Saved pdf report to \"" + reportGenerator.getFilePath() + "\"!");
    }//GEN-LAST:event_btnGeneratePdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vaccination_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vaccination_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vaccination_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vaccination_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vaccination_Status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneratePdf;
    private javax.swing.JButton btnGenerateTxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblPersonalDetails;
    private javax.swing.JLabel lblVaccination1;
    private javax.swing.JLabel lblVaccination2;
    // End of variables declaration//GEN-END:variables

    private void initInformation() {
        lblPersonalDetails.setText(utils.Util.convertStringToHtmlString(people.getGenerateContent()));
        People p = peopleDao.get(people.getKey()); // getting data from data file instead of static runtime
        System.out.println(p.getVaccinations().size());
        for (int i = 0; i < p.getVaccinations().size(); i++) {
            javax.swing.JLabel lbl = null;
            if (i == 0) {
                lbl = lblVaccination1;
            } else {
                lbl = lblVaccination2;
            }
            String vaccinationDetails = p.getVaccinations().get(i).getGenerateContent();
            lbl.setText(utils.Util.convertStringToHtmlString(vaccinationDetails));
        }


    }
}
